# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "qr-code-app"
client_id = "554f91daa44403e93b5ea48e0f206e42"
application_url = "https://exports-travesti-interim-finances.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://exports-travesti-interim-finances.trycloudflare.com/auth/callback",
  "https://exports-travesti-interim-finances.trycloudflare.com/auth/shopify/callback",
  "https://exports-travesti-interim-finances.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "practicestoreapp2.myshopify.com"
